### ISSUE TITLE
unable to successfully install and run nslocalizer

### ISSUE THREAD

**Issue by tymrtn** [samdmarshall/nslocalizer#7]
**Type of issue**: Bug

---

**Related Files**: 
https://gist.github.com/c859ec7ca61130369fc40bea3b53b9a8

---

**Description**:
Followed all install instructions, but am getting "command not found" when running nslocalizer. Install seems to fail on install_requirements.txt, after which it prints:
`If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/samdmarshall/homebrew-formulae/issues`

I followed all brew/Troubleshooting instructions, updated my XCode command line tools, restarted everything... no effect. I have also tried installing python3, but it says it's already installed. 

---

**Comment by samdmarshall** [comment]
I will need to see the logs of what happens when it installs (and the output of pip3).

**Comment by tymrtn** [comment]
Can you point me in the direction of how to get those logs? Nothing helpful is shown in terminal.

**Comment by samdmarshall** [comment]
if you run `brew install nslocalizer` can you gist the entire output of that? you have the the brew logs but not the logs of the actions that happen, so i don't know why the `pip3 install -r install_requirements.txt` is failing for you.

**Comment by tymrtn** [comment]
When I run `brew install nslocalizer` this is what I get:

```
My Computers Name:~ username$ brew install nslocalizer
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, samdmarshall/formulae).
==> New Formulae
arx-libertatis                           magnetix
autorest                                 mingw-w64
boost-mpi                                openmsx
chocolate-doom                           samdmarshall/formulae/dagger
elasticsearch@2.3                        samdmarshall/formulae/omni
httest                                   simutrans
kompose
==> Updated Formulae
ansible-cmdb               google-java-format         redis
antigen                    ironcli                    scriptcs
aws-sdk-cpp                jenkins                    scrypt
awscli                     juju                       snap-telemetry
bash-preexec               juju@1.25                  svtplay-dl
chakra                     kerl                       swiftformat
citus                      kobalt                     temporal_tables
dark-mode                  libmagic                   terragrunt
digdag                     mcabber                    tomcat@8.0
docker-completion          mpv                        ttyd
docker-machine-completion  mypy                       vim
dub                        pkcs11-helper              wakatime-cli
flow                       planck                     wartremover
fon-flash-cli              prometheus                 wget
fonttools                  purescript                 yadm
gofabric8                  puzzles                    youtube-dl
==> Deleted Formulae
mingw-w64-binutils

==> Installing nslocalizer from samdmarshall/formulae
==> Downloading https://github.com/samdmarshall/nslocalizer/archive/v1.0.1.zip
Already downloaded: /Users/tylermartin/Library/Caches/Homebrew/nslocalizer-1.0.1.zip
==> pip3 install -r install_requirements.txt
Last 15 lines from /Users/tylermartin/Library/Logs/Homebrew/nslocalizer/01.pip3:
2017-02-13 12:58:44 -0600

pip3
install
-r
install_requirements.txt


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/samdmarshall/homebrew-formulae/issues

My Computers Name:~ username$ nslocalizer
-bash: nslocalizer: command not found
```

(thanks for looking into this)

**Comment by samdmarshall** [comment]
Oops, my apologies, i need to see it run like this: `brew install nslocalizer --verbose --debug` (i forgot i have the verbose flag turned on by default)

**Comment by tymrtn** [comment]
Oh okay, cool. I fixed it from reading this thread: https://github.com/Homebrew/legacy-homebrew/issues/35404

Required `brew reinstall python3`

Thanks again!

**Comment by samdmarshall** [comment]
awesome, glad it worked for you. I can look at the formula and see if there is a way to provide some info if the pip3 install fails.

**Comment by maksumon** [comment]
Cannot install on High Sierra 10.13.6 with following error:

==> pip3 install -r install_requirements.txt
Last 15 lines from /Users/maksumon/Library/Logs/Homebrew/nslocalizer/01.pip3:
  Running setup.py bdist_wheel for pbPlist: finished with status 'done'
  Stored in directory: /private/tmp/nslocalizer-20180823-47905-py2ydq/nslocalizer-1.0.1/.brew_home/Library/Caches/pip/wheels/f3/20/a2/f079fc4cb3b180d2266a8846035b5d1fee29be79c65d61d300
  Running setup.py bdist_wheel for langcodes: started
  Running setup.py bdist_wheel for langcodes: finished with status 'done'
  Stored in directory: /private/tmp/nslocalizer-20180823-47905-py2ydq/nslocalizer-1.0.1/.brew_home/Library/Caches/pip/wheels/84/20/3d/dc2010b4f7c0b786a06947530a962972caead0c58898f25a02
  Running setup.py bdist_wheel for biplist: started
  Running setup.py bdist_wheel for biplist: finished with status 'done'
  Stored in directory: /private/tmp/nslocalizer-20180823-47905-py2ydq/nslocalizer-1.0.1/.brew_home/Library/Caches/pip/wheels/e1/a5/ce/28ba6a80c2487f54deec4a2eda7ccda8bcbeeec2aad39e9779
  Running setup.py bdist_wheel for marisa-trie: started
  Running setup.py bdist_wheel for marisa-trie: finished with status 'done'
  Stored in directory: /private/tmp/nslocalizer-20180823-47905-py2ydq/nslocalizer-1.0.1/.brew_home/Library/Caches/pip/wheels/45/24/79/022624fc914f0e559fe8a1141aaff1f9df810905a13fc75d57
Successfully built pbPlist langcodes biplist marisa-trie
Installing collected packages: pyobjc-core, pyobjc-framework-Cocoa, biplist, pbPlist, marisa-trie, langcodes
Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/usr/local/lib/python3.7/site-packages/pyobjc_core-4.2.2-py3.7-nspkg.pth'

**Comment by samdmarshall** [comment]
again, this seems to be a problem with the pyobjc libraries being installed, which are outside the scope of this project.
